ServerEvents.tags('item', event => {
  event.add('astral:boiler', 'gtceu:lp_steam_solid_boiler')
  event.add('astral:boiler', 'gtceu:hp_steam_solid_boiler')
  event.add('astral:boiler', 'gtceu:lp_steam_liquid_boiler')
  event.add('astral:boiler', 'gtceu:hp_steam_liquid_boiler')
  event.add('astral:boiler', 'gtceu:lp_steam_solar_boiler')
  event.add('astral:boiler', 'gtceu:hp_steam_solar_boiler')
  event.add('astral:boiler', 'gtceu:bronze_large_boiler')
  event.add('astral:boiler', 'gtceu:steel_large_boiler')
  event.add('astral:boiler', 'gtceu:titanium_large_boiler')
  event.add('astral:boiler', 'gtceu:tungstensteel_large_boiler')
  
  event.add('gtceu:rubber_logs', 'gtceu:rubber_log')
  event.add('gtceu:rubber_logs', 'gtceu:stripped_rubber_log')
  event.add('gtceu:rubber_logs', 'gtceu:rubber_wood')
  event.add('gtceu:rubber_logs', 'gtceu:stripped_rubber_wood')
})
