ServerEvents.tags('item', event => {
  event.add('forge:furnaces/basic', 'minecraft:furnace')
  event.add('forge:furnaces/basic', 'quark:deepslate_furnace')
  event.add('forge:furnaces/blackstone', 'quark:blackstone_furnace')
  event.add('forge:furnaces/blackstone', 'nethersdelight:blackstone_furnace')

  event.add('forge:stones/furnace/basic', 'minecraft:stone')
  event.add('forge:stones/furnace/basic', 'minecraft:cobblestone')
  event.add('forge:stones/furnace/basic', '#minecraft:stone_bricks')
  event.add('forge:stones/furnace/basic', 'minecraft:andesite')
  event.add('forge:stones/furnace/basic', 'minecraft:granite')
  event.add('forge:stones/furnace/basic', 'minecraft:end_stone')
  event.add('forge:stones/furnace/basic', 'alexscaves:limestone')
  event.add('forge:stones/furnace/basic', 'alexscaves:limestone_pillar')
  event.add('forge:stones/furnace/basic', 'alexscaves:chiseled_limestone')
  event.add('forge:stones/furnace/basic', 'alexscaves:smooth_limestone')
  event.add('forge:stones/furnace/basic', 'alexscaves:limestone')
  event.add('forge:stones/furnace/basic', 'alexscaves:guanostone')
  event.add('forge:stones/furnace/deepslate', 'minecraft:deepslate')
  event.add('forge:stones/furnace/deepslate', 'minecraft:cobbled_deepslate')
  event.add('forge:stones/furnace/deepslate', 'minecraft:chiseled_deepslate')
  event.add('forge:stones/furnace/deepslate', 'minecraft:polished_deepslate')
  event.add('forge:stones/furnace/deepslate', 'minecraft:deepslate_bricks')
  event.add('forge:stones/furnace/deepslate', 'minecraft:cracked_deepslate_bricks')
  event.add('forge:stones/furnace/deepslate', 'minecraft:deepslate_tiles')
  event.add('forge:stones/furnace/deepslate', 'minecraft:cracked_deepslate_tiles')
  event.add('forge:stones/furnace/deepslate', 'alexscaves:abyssmarine')
  event.add('forge:stones/furnace/deepslate', 'alexscaves:abyssmarine_bricks')
  event.add('forge:stones/furnace/deepslate', 'alexscaves:abyssmarine_pillar')
  event.add('forge:stones/furnace/deepslate', 'alexscaves:abyssmarine_tiles')
  event.add('forge:stones/furnace/blackstone', 'minecraft:blackstone')
  event.add('forge:stones/furnace/blackstone', 'minecraft:gilded_blackstone')
  event.add('forge:stones/furnace/blackstone', 'minecraft:chiseled_polished_blackstone')
  event.add('forge:stones/furnace/blackstone', 'minecraft:polished_blackstone')
  event.add('forge:stones/furnace/blackstone', 'minecraft:polished_blackstone_bricks')
  event.add('forge:stones/furnace/blackstone', 'minecraft:cracked_polished_blackstone_bricks')
  event.add('forge:stones/furnace/blackstone', 'minecraft:blackstone_bricks')
  event.add('forge:stones/furnace/blackstone', 'minecraft:blackstone')


  event.add('astral:hammer', '#forge:tools/mallets')
  event.add('astral:hammer', '#forge:tools/hammers')
  event.add('astral:tool_flint', 'kubejs:sword_flint')
  event.add('astral:tool_flint', 'kubejs:pickaxe_flint')
  event.add('astral:tool_flint', 'kubejs:axe_flint')
  event.add('astral:tool_flint', 'kubejs:shovel_flint')
  event.add('astral:tool_flint', 'kubejs:hoe_flint')

  event.add('astral:binding', 'minecraft:string')
  event.add('astral:binding', 'gtceu:sticky_resin')

  event.add('forge:ropes', 'quark:rope')
  event.add('forge:ropes', 'farmersdelight:rope')

  event.add('astral:chain_ring', 'gtceu:iron_ring')
  event.add('astral:chain_ring', 'gtceu:wrought_iron_ring')
  event.add('astral:chain_ring', 'gtceu:steel_ring')
  event.add('astral:chain_ring', 'gtceu:stainless_steel_ring')
  event.add('astral:chain_ring', 'gtceu:tungstensteel_ring')

  event.add('astral:lantern_base', 'gtceu:iron_plate')
  event.add('astral:lantern_base', 'gtceu:wrought_iron_plate')
  event.add('astral:lantern_base', 'kubejs:ironwood_plate')
  event.add('astral:lantern_base', 'gtceu:steel_plate')
  event.add('astral:lantern_base', 'gtceu:damascus_steel_plate')
  event.add('astral:lantern_base', 'gtceu:black_steel_plate')
  event.add('astral:lantern_base', 'gtceu:vanadium_steel_plate')
  event.add('astral:lantern_base', 'gtceu:tungsten_steel_plate')
  event.add('astral:lantern_base', 'gtceu:stainless_steel_plate')
  event.add('astral:lantern_base', 'gtceu:red_steel_plate')
  event.add('astral:lantern_base', 'gtceu:blue_steel_plate')
  event.add('astral:lantern_base', 'gtceu:hsla_steel_plate')
  event.add('astral:lantern_base', 'gtceu:watertight_steel_plate')
  event.add('astral:lantern_base', 'gtceu:maraging_steel_3000_plate')

  event.add('astral:lantern_rod', 'gtceu:iron_rod')
  event.add('astral:lantern_rod', 'gtceu:magnetic_iron_rod')
  event.add('astral:lantern_rod', 'gtceu:wrought_iron_rod')
  event.add('astral:lantern_rod', 'gtceu:steel_rod')
  event.add('astral:lantern_rod', 'gtceu:magnetic_steel_rod')
  event.add('astral:lantern_rod', 'gtceu:damascus_steel_rod')
  event.add('astral:lantern_rod', 'gtceu:black_steel_rod')
  event.add('astral:lantern_rod', 'gtceu:vanadium_steel_rod')
  event.add('astral:lantern_rod', 'gtceu:tungsten_steel_rod')
  event.add('astral:lantern_rod', 'gtceu:stainless_steel_rod')
  event.add('astral:lantern_rod', 'gtceu:red_steel_rod')
  event.add('astral:lantern_rod', 'gtceu:blue_steel_rod')
  event.add('astral:lantern_rod', 'gtceu:hsla_steel_rod')
  event.add('astral:lantern_rod', 'gtceu:watertight_steel_rod')
  event.add('astral:lantern_rod', 'gtceu:maraging_steel_3000_rod')

  event.add('astral:arrowhead', 'minecraft:flint')
  event.add('astral:arrowhead', 'minecraft:iron_nugget')
  event.add('astral:arrowhead', 'gtceu:stainless_steel_nugget')
  event.add('astral:arrowhead', 'gtceu:steel_nugget')
  event.add('astral:arrowhead', 'gtceu:copper_nugget')
  event.add('forge:feathers', 'alexsmobs:roadrunner_feather')
  event.add('forge:feathers', 'alexsmobs:emu_feather')
  event.add('astral:fletching', '#forge:feathers')
  event.add('astral:fletching', 'gtceu:wood_plate')
  event.add('astral:fletching', 'gtceu:empty_wooden_form')
  event.add('astral:fletching', 'gtceu:polyvinyl_chloride_plate')

  event.add('forge:dyes/black', 'gtceu:carbon_dust')
  event.add('forge:dyes/black', 'gtceu:graphene_dust')
  event.add('forge:dyes/black', 'gtceu:graphite_dust')
  event.add('forge:dyes/black', 'gtceu:charcoal_dust')
  event.add('forge:dyes/black', 'gtceu:coal_dust')
  event.add('forge:dyes/brown', 'gtceu:goethite_dust')
  event.add('forge:dyes/yellow', 'gtceu:yellow_limonite_dust')
  event.add('forge:dyes/red', 'gtceu:hematite_dust')

  event.add('forge:waxes', 'kubejs:wax')
  event.add('forge:waxes', 'minecraft:honeycomb')
  
  event.add('forge:wood_finishes', '#forge:waxes')
  event.add('forge:wood_finishes', '#forge:oils/walnut')
  event.add('forge:wood_finishes', '#forge:oils/tung')
  event.add('forge:wood_finishes', '#forge:oils/linseed')
  event.add('forge:wood_finishes', '#forge:oils/flax')
  

  event.add('astral:fiber_string', 'minecraft:wheat')
  event.add('astral:fiber_string', '#forge:crops/barley')
  event.add('astral:fiber_string', '#forge:crops/amaranth')
  event.add('astral:fiber_string', '#forge:crops/oats')
  event.add('astral:fiber_string', '#forge:crops/rice')
  event.add('astral:fiber_string', '#forge:crops/rye')
  event.add('astral:fiber_string', '#forge:crops/cattail')
  event.add('astral:fiber_string', '#forge:crops/sorghum')
  event.add('astral:fiber_string', 'minecraft:grass')
  event.add('astral:fiber_string', 'minecraft:vine')
  event.add('astral:fiber_string', 'minecraft:twisting_vines')
  event.add('astral:fiber_string', 'minecraft:weeping_vines')
  event.add('astral:fiber_string', 'minecraft:tall_grass')
  event.add('astral:fiber_string', 'biomesoplenty:high_grass')
  event.add('astral:fiber_string', 'biomesoplenty:dune_grass')
  event.add('astral:fiber_string', 'biomesoplenty:water_grass')
  event.add('astral:fiber_string', 'biomesoplenty:willow_vine')
  event.add('astral:fiber_string', 'alexscaves:archaic_vine')
  event.add('astral:fiber_string', 'farmersdelight:straw')

  event.add('astral:lantern_fuel_solid', 'torch')
  event.add('astral:lantern_fuel_liquid', '#forge:cookingoil')
  event.add('astral:lantern_fuel_liquid', 'pamhc2foodcore:butter')
  event.add('astral:lantern_fuel_liquid', 'kubejs:shortening')
  event.add('astral:lantern_fuel_liquid', '#forge:waxes')
  event.add('astral:lantern_fuel_liquid', 'gtceu:creosote_bucket')
  event.add('astral:lantern_fuel_liquid', 'gtceu:seed_oil_bucket')
  event.add('astral:lantern_fuel_liquid', 'gtceu:oil_bucket')
  event.add('astral:lantern_fuel_liquid', 'gtceu:oil_heavy_bucket')
  event.add('astral:lantern_fuel_liquid', 'gtceu:oil_medium_bucket')
  event.add('astral:lantern_fuel_liquid', 'gtceu:oil__light_bucket')
  event.add('astral:lantern_fuel_liquid', 'gtceu:fish_oil_bucket')
  event.add('astral:lantern_fuel_liquid', 'gtceu:sticky_resin')
  event.add('astral:lantern_soul_fuel_solid', 'soul_torch')
  event.add('astral:lantern_soul_fuel_liquid', 'soul_sand')
  event.add('astral:lantern_soul_fuel_liquid', 'soul_soil')
})
