//requires: gregifiedintegrations
//requires: twilightforest
ServerEvents.recipes(event => {
event.remove({ id: 'twilightforest:wood/twilight_oak_trapdoor' })
event.remove({ id: 'twilightforest:wood/canopy_trapdoor' })
event.remove({ id: 'twilightforest:wood/mangrove_trapdoor' })
event.remove({ id: 'twilightforest:wood/dark_trapdoor' })
event.remove({ id: 'twilightforest:wood/time_trapdoor' })
event.remove({ id: 'twilightforest:wood/transformation_trapdoor' })
event.remove({ id: 'twilightforest:wood/mining_trapdoor' })
event.remove({ id: 'twilightforest:wood/sorting_trapdoor' })
event.remove({ id: 'twilightforest:wood/twilight_oak_door' })
event.remove({ id: 'twilightforest:wood/canopy_door' })
event.remove({ id: 'twilightforest:wood/mangrove_door' })
event.remove({ id: 'twilightforest:wood/dark_door' })
event.remove({ id: 'twilightforest:wood/time_door' })
event.remove({ id: 'twilightforest:wood/transformation_door' })
event.remove({ id: 'twilightforest:wood/mining_door' })
event.remove({ id: 'twilightforest:wood/sorting_door' })
})