// Listen to item tag event
ServerEvents.tags('item', event => {
  event.remove('terralith:spire/junk_tools', 'minecraft:stone_pickaxe')
  event.remove('terralith:spire/junk_tools', 'minecraft:stone_sword')
  event.remove('terralith:spire/junk_tools', 'minecraft:wooden_axe')
  event.remove('terralith:spire/junk_tools', 'minecraft:wooden_pickaxe')
  event.remove('terralith:spire/junk_tools', 'mminecraft:wooden_shovel')
  event.add('terralith:spire/junk_tools', 'kubejs:shovel_flint')
  event.add('terralith:spire/junk_tools', 'kubejs:pickaxe_flint')
  event.add('terralith:spire/junk_tools', 'kubejs:axe_flint')
  event.add('terralith:spire/junk_tools', 'kubejs:sword_flint')
  event.add('terralith:spire/junk_tools', 'kubejs:hoe_flint')
  event.add('terralith:spire/junk_tools', 'gtceu:flint_knife')
  event.add('terralith:spire/junk_tools', 'gtceu:steel_saw')
  
  event.remove('terralith:spire/common_tools', 'minecraft:iron_axe')
  event.remove('terralith:spire/common_tools', 'minecraft:iron_pickaxe')
  event.remove('terralith:spire/common_tools', 'minecraft:iron_shovel')
  event.remove('terralith:spire/common_tools', 'minecraft:iron_sword')
  event.add('terralith:spire/common_tools', 'gtceu:iron_axe')
  event.add('terralith:spire/common_tools', 'gtceu:iron_pickaxe')
  event.add('terralith:spire/common_tools', 'gtceu:iron_shovel')
  event.add('terralith:spire/common_tools', 'gtceu:iron_sword')
  event.add('terralith:spire/common_tools', 'gtceu:iron_knife')
  event.add('terralith:spire/common_tools', 'gtceu:iron_hammer')
  event.add('terralith:spire/common_tools', 'gtceu:iron_file')
  event.add('terralith:spire/common_tools', 'gtceu:iron_saw')
  event.add('terralith:spire/common_tools', 'gtceu:invar_axe')
  event.add('terralith:spire/common_tools', 'gtceu:invar_pickaxe')
  event.add('terralith:spire/common_tools', 'gtceu:invar_shovel')
  event.add('terralith:spire/common_tools', 'gtceu:invar_sword')
  event.add('terralith:spire/common_tools', 'gtceu:invar_knife')
  event.add('terralith:spire/common_tools', 'gtceu:invar_hammer')
  event.add('terralith:spire/common_tools', 'gtceu:invar_file')
  event.add('terralith:spire/common_tools', 'gtceu:invar_saw')
  event.add('terralith:spire/common_tools', 'gtceu:wrought_iron_axe')
  event.add('terralith:spire/common_tools', 'gtceu:wrought_iron_pickaxe')
  event.add('terralith:spire/common_tools', 'gtceu:wrought_iron_shovel')
  event.add('terralith:spire/common_tools', 'gtceu:wrought_iron_sword')
  event.add('terralith:spire/common_tools', 'gtceu:wrought_iron_knife')
  event.add('terralith:spire/common_tools', 'gtceu:wrought_iron_hammer')
  event.add('terralith:spire/common_tools', 'gtceu:wrought_iron_file')
  event.add('terralith:spire/common_tools', 'gtceu:wrought_iron_saw')
  event.add('terralith:spire/common_tools', 'gtceu:wood_mallet')

  event.add('terralith:spire/rare_tools', 'gtceu:steel_axe')
  event.add('terralith:spire/rare_tools', 'gtceu:steel_pickaxe')
  event.add('terralith:spire/rare_tools', 'gtceu:steel_shovel')
  event.add('terralith:spire/rare_tools', 'gtceu:steel_sword')
  event.add('terralith:spire/rare_tools', 'gtceu:steel_knife')
  event.add('terralith:spire/rare_tools', 'gtceu:steel_hammer')
  event.add('terralith:spire/rare_tools', 'gtceu:steel_file')
  event.add('terralith:spire/rare_tools', 'gtceu:steel_saw')
  event.add('terralith:spire/rare_tools', 'gtceu:damascus_steel_axe')
  event.add('terralith:spire/rare_tools', 'gtceu:damascus_steel_pickaxe')
  event.add('terralith:spire/rare_tools', 'gtceu:damascus_steel_shovel')
  event.add('terralith:spire/rare_tools', 'gtceu:damascus_steel_sword')
  event.add('terralith:spire/rare_tools', 'gtceu:damascus_steel_knife')
  event.add('terralith:spire/rare_tools', 'gtceu:damascus_steel_hammer')
  event.add('terralith:spire/rare_tools', 'gtceu:damascus_steel_file')
  event.add('terralith:spire/rare_tools', 'gtceu:damascus_steel_saw')


  event.remove('terralith:spire/diamond', 'minecraft:diamond_ore')
  event.remove('terralith:spire/diamond', 'minecraft:deepslate_diamond_ore')
  event.add('terralith:spire/diamond', 'gtceu:raw_diamond')
  event.add('terralith:spire/diamond', 'gtceu:diamond_ore')
  event.add('terralith:spire/diamond', 'gtceu:deepslate_diamond_ore')
})
