//requires: alexscaves
//requires: gtceu
GTCEuStartupEvents.registry('gtceu:tag_prefix', event => {
    event.create('galena', 'ore')
        .stateSupplier(() => Block.getBlock('alexscaves:galena').defaultBlockState())
        .baseModelLocation('alexscaves:block/galena')
        .unificationEnabled(true)
        .materialIconType(GTMaterialIconType.ore)
        .generationCondition(ItemGenerationCondition.hasOreProperty)
    event.create('limestone', 'ore')
        .stateSupplier(() => Block.getBlock('alexscaves:limestone').defaultBlockState())
        .baseModelLocation('alexscaves:block/limestone')
        .unificationEnabled(true)
        .materialIconType(GTMaterialIconType.ore)
        .generationCondition(ItemGenerationCondition.hasOreProperty)
    event.create('radrock', 'ore')
        .stateSupplier(() => Block.getBlock('alexscaves:radrock').defaultBlockState())
        .baseModelLocation('alexscaves:block/radrock')
        .unificationEnabled(true)
        .materialIconType(GTMaterialIconType.ore)
        .generationCondition(ItemGenerationCondition.hasOreProperty)
    event.create('abyssmarine', 'ore')
        .stateSupplier(() => Block.getBlock('alexscaves:abyssmarine').defaultBlockState())
        .baseModelLocation('alexscaves:block/abyssmarine')
        .unificationEnabled(true)
        .materialIconType(GTMaterialIconType.ore)
        .generationCondition(ItemGenerationCondition.hasOreProperty)
    event.create('guanostone', 'ore')
        .stateSupplier(() => Block.getBlock('alexscaves:guanostone').defaultBlockState())
        .baseModelLocation('alexscaves:block/guanostone')
        .unificationEnabled(true)
        .materialIconType(GTMaterialIconType.ore)
        .generationCondition(ItemGenerationCondition.hasOreProperty)
})